# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diana Delvasto
email: d@startics.com
description: > # this means to ignore newlines until "baseurl:"
  Entrenadora vocal con trayectoria en artistas cristianos y seculares de la talla de Alex Campos, Cristi Corson y la esposa de Falcao.
  Clases particulares y talleres grupales para iglesias, corales y tunas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://d.startics.com" # the base hostname & protocol for your site
twitter_username: dianadelvasto
github_username: camilodelvasto

# Build settings
#markdown: kramdown

# Lib settings (useful for keeping the lib folder during the build)
include: ["_lib"]
